INSERT INTO MEDICATION (MEDICATION_ID, NAME, WEIGHT, CODE) VALUES (1, 'Paracetamol', 10, '12345');
INSERT INTO MEDICATION (MEDICATION_ID, NAME, WEIGHT, CODE) VALUES (2, 'acetaminophen', 15, '12346');
INSERT INTO MEDICATION (MEDICATION_ID, NAME, WEIGHT, CODE) VALUES (3, 'dolex', 34, '12347');
INSERT INTO MEDICATION (MEDICATION_ID, NAME, WEIGHT, CODE) VALUES (4, 'aspirin', 56, '12348');